name: Rust CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 0 1 * *" # monthly
  workflow_dispatch: # allow manual triggering of the action

env:
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"
jobs:
  build-x86:
    name: Build and test crate/docs
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
        toolchain: ["1.88", nightly, beta, stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rust-docs

        # Default build, no features
      - name: Build library
        run: cargo build -v --lib --no-default-features
      - name: Test library
        run: cargo test --no-default-features --lib
      - name: Doc tests
        run: cargo test --no-default-features --doc
      - name: Build docs
        run: cargo doc --no-deps --no-default-features

        # AVX intrinsics testing
      - name: Test library (avx feature)
        run: cargo test --no-default-features --lib --features _avx_test

        # Nightly feature tests
      - name: Test library (nightly feature)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo test --no-default-features --lib --features nightly
      - name: Doc tests (nightly feature)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo test --no-default-features --doc --features nightly
      - name: Build docs (nightly feature)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo doc --no-deps --no-default-features --features nightly

  build-aarch64:
    name: Build and test crate
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos]
        toolchain: ["1.88", nightly, beta, stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rust-docs
          targets: aarch64-apple-darwin

        # Default build, no features
      - name: Build library
        run: cargo build -v --lib --no-default-features --target aarch64-apple-darwin
      - name: Test library
        run: cargo test --no-default-features --lib --target aarch64-apple-darwin
      - name: Doc tests
        run: cargo test --no-default-features --doc --target aarch64-apple-darwin
      - name: Build docs
        run: cargo doc --no-deps --no-default-features --target aarch64-apple-darwin

        # Nightly feature tests
      - name: Test library (nightly feature)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo test --no-default-features --lib --features nightly
      - name: Doc tests (nightly feature)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo test --no-default-features --doc --features nightly
      - name: Build docs (nightly feature)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo doc --no-deps --no-default-features --features nightly

  clippy-rustfmt:
    name: Clippy and rustfmt
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: clippy
        run: cargo clippy
        continue-on-error: true
      - name: rustfmt
        run: cargo fmt -- --check
        continue-on-error: true

  codegen-x86:
    name: x86_64 assembly codegen tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cache LLVM build/bin/ directory
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/llvmbuild/bin/
          key: ${{ runner.os }}-llvm-20

      - name: Download LLVM and build FileCheck
        # FileCheck doesn't exist because the cache wasn't hit, rebuild it
        if: ${{ hashFiles('llvmbuild/bin/FileCheck') == '' }}
        run: |
          # Prepare build environment
          sudo apt -y update
          sudo apt -y install build-essential cmake xz-utils lsb-release wget software-properties-common
          sudo apt -y autoremove
          # Download LLVM source
          wget https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-20.1.8.tar.gz
          tar -xf llvmorg-20.1.8.tar.gz
          # Configure the target and build folder, FileCheck requires enabling -DLLVM_INSTALL_UTILS=ON
          mkdir llvmbuild
          cmake -S ${{ github.workspace }}/llvm-project-llvmorg-20.1.8/llvm/ -B ${{ github.workspace }}/llvmbuild/ -DCMAKE_BUILD_TYPE=Release -DLLVM_INSTALL_UTILS=ON
          cmake --build ${{ github.workspace }}/llvmbuild/ --target FileCheck

      - name: Store FileCheck path in ENV variable
        run: echo "FILECHECK=${{ github.workspace }}/llvmbuild/bin/FileCheck" >> $GITHUB_ENV

      - name: Run assembly tests
        run: cargo test --features _assembly_x86

  miri:
    name: Miri
    runs-on: ubuntu-latest
    needs: [build-x86, build-aarch64]
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri, Linux 64-bit x86_64 target
        run: RUSTFLAGS="-Dwarnings -Ctarget-feature=+avx" cargo miri test --features _avx_test,nightly --target x86_64-unknown-linux-gnu
      - name: Test with Miri, Linux 32-bit x86 target
        run: RUSTFLAGS="-Dwarnings -Ctarget-feature=+avx" cargo miri test --features _avx_test,nightly --target i686-unknown-linux-gnu
      - name: Test with Miri, Linux 64-bit aarch64 target
        run: RUSTFLAGS="-Dwarnings" cargo miri test --features nightly --all-features --target aarch64-unknown-linux-gnu
